
export class DashboardDefault {
  public graphs: string

  constructor() {
    this.graphs=`
    [
      {
        "id": "graph2",
        "x": 10,
        "y": 20,
        "width": 300,
        "height": 90,
        "type": "counterSquare",
        "fields": [],
        "title": "Stacks CPU: ",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": true,
        "alertMin": "30",
        "alertMax": "100",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "cpu-usage",
        "counterHorizontal": true,
        "requestId": "graph2"
      },
      {
        "id": "graph3",
        "x": 10,
        "y": 130,
        "width": 300,
        "height": 90,
        "type": "counterSquare",
        "fields": [],
        "title": "Stacks Mem: ",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": true,
        "alertMin": "4GB",
        "alertMax": "7GB",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "mem-usage",
        "counterHorizontal": true,
        "requestId": "graph3"
      },
      {
        "id": "graph4",
        "x": 10,
        "y": 240,
        "width": 300,
        "height": 100,
        "type": "counterSquare",
        "fields": [],
        "title": "Stacks Net: ",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": true,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "net-total-bytes",
        "counterHorizontal": true,
        "requestId": "graph4"
      },
      {
        "id": "graph5",
        "x": 10,
        "y": 360,
        "width": 300,
        "height": 100,
        "type": "counterSquare",
        "fields": [],
        "title": "Stacks IO: ",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": true,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "io-total",
        "counterHorizontal": true,
        "requestId": "graph5"
      },
      {
        "id": "graph6",
        "x": 440,
        "y": 20,
        "width": 210,
        "height": 50,
        "type": "counterSquare",
        "fields": [],
        "title": "Stack number: ",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": true,
        "alertMin": "",
        "alertMax": "1",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "stack",
        "field": "number",
        "counterHorizontal": true,
        "requestId": "graph6"
      },
      {
        "id": "graph7",
        "x": 440,
        "y": 80,
        "width": 210,
        "height": 50,
        "type": "counterSquare",
        "fields": [],
        "title": "Service number: ",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": true,
        "alertMin": "",
        "alertMax": "10",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "service",
        "field": "number",
        "counterHorizontal": true,
        "requestId": "graph7"
      },
      {
        "id": "graph8",
        "x": 440,
        "y": 140,
        "width": 210,
        "height": 50,
        "type": "counterSquare",
        "fields": [],
        "title": "Container number: ",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": true,
        "alertMin": "",
        "alertMax": "14",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "container",
        "field": "number",
        "counterHorizontal": true,
        "requestId": "graph8"
      },
      {
        "id": "graph9",
        "x": 670,
        "y": 200,
        "width": 530,
        "height": 260,
        "type": "bubbles",
        "fields": [],
        "title": "5 first services CPU/Mem size: Net",
        "border": true,
        "modeParameter": false,
        "topNumber": 5,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "service",
        "field": "net-total-bytes",
        "bubbleXField": "mem-usage",
        "bubbleYField": "cpu-usage",
        "bubbleScale": "medium",
        "requestId": "graph9"
      },
      {
        "id": "graph10",
        "x": 670,
        "y": 20,
        "width": 170,
        "height": 170,
        "type": "pie",
        "fields": [],
        "title": "CPU: 3 First services",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "service",
        "field": "cpu-usage",
        "requestId": "graph10"
      },
      {
        "id": "graph11",
        "x": 1030,
        "y": 20,
        "width": 170,
        "height": 170,
        "type": "pie",
        "fields": [],
        "title": "Net: 3 first services",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "service",
        "field": "net-total-bytes",
        "requestId": "graph11"
      },
      {
        "id": "graph12",
        "x": 850,
        "y": 20,
        "width": 170,
        "height": 170,
        "type": "pie",
        "fields": [],
        "title": "Mem: 3 First services",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "service",
        "field": "mem-usage",
        "requestId": "graph12"
      },
      {
        "id": "graph13",
        "x": 440,
        "y": 200,
        "width": 210,
        "height": 210,
        "type": "legend",
        "fields": [],
        "title": "Legend services",
        "border": false,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "service",
        "transparentLegend": false
      },
      {
        "id": "graph14",
        "x": 320,
        "y": 20,
        "width": 100,
        "height": 90,
        "type": "lines",
        "fields": [],
        "title": "all",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "cpu-usage",
        "histoPeriod": "now-30m",
        "requestId": "graph14",
        "yTitle": "cpu usage",
        "histoStep": "1m"
      },
      {
        "id": "graph15",
        "x": 320,
        "y": 130,
        "width": 100,
        "height": 90,
        "type": "lines",
        "fields": [],
        "title": "all",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "mem-usage",
        "histoPeriod": "now-30m",
        "requestId": "graph15",
        "yTitle": "cpu usage",
        "histoStep": "1m"
      },
      {
        "id": "graph16",
        "x": 320,
        "y": 240,
        "width": 100,
        "height": 100,
        "type": "lines",
        "fields": [],
        "title": "all",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "net-total-bytes",
        "histoPeriod": "now-30m",
        "requestId": "graph16",
        "yTitle": "cpu usage",
        "histoStep": "1m"
      },
      {
        "id": "graph17",
        "x": 320,
        "y": 360,
        "width": 100,
        "height": 100,
        "type": "lines",
        "fields": [],
        "title": "all",
        "border": true,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "all",
        "field": "cpu-usage",
        "histoPeriod": "now-30m",
        "requestId": "graph17",
        "yTitle": "cpu usage",
        "histoStep": "1m"
      },
      {
        "id": "graph18",
        "x": 320,
        "y": 0,
        "width": 100,
        "height": 20,
        "type": "text",
        "fields": [],
        "title": "30 min",
        "border": false,
        "modeParameter": false,
        "topNumber": 3,
        "alert": false,
        "alertMin": "",
        "alertMax": "",
        "criterion": "",
        "criterionValue": "",
        "stackedAreas": true,
        "legendNames": [],
        "legendColors": [],
        "containerAvg": false,
        "roundedBox": true,
        "object": "stack",
        "field": "cpu-usage",
        "requestId": "graph18"
      }
    ]
`
}
}
